services:
  mysql:
    image: mysql:8.0
    container_name: nest_mysql_auth
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: auth_pass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - nest-network

  mysql_messenger:
    image: mysql:8.0
    container_name: nest_mysql_messenger
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: messenger_db
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: auth_pass
    volumes:
      - mysql_messenger_data:/var/lib/mysql
    networks:
      - nest-network

  nats:
    image: nats:2.10-alpine
    container_name: nest_nats
    ports:
      - '4222:4222'
      - '8222:8222' # HTTP monitoring port
    command: ['-js', '-m', '8222'] # Enable JetStream and monitoring
    networks:
      - nest-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      # Exposes 29092 for external connections to the broker
      - '29092:29092'
      # Exposes 9092 for internal connections to the broker
      - '9092:9092'
      # Controller port for KRaft
      - '9093:9093'
    environment:
      # KRaft mode configuration
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093,PLAINTEXT_HOST://0.0.0.0:29092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      # Storage configuration
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
      # logging configuration to reduce metadata loader verbosity
      KAFKA_LOG4J_LOGGERS: 'org.apache.kafka.image.loader.MetadataLoader=WARN'
      KAFKA_LOG4J_ROOT_LOGLEVEL: 'INFO'
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - nest-network

volumes:
  mysql_data:
  mysql_messenger_data:
  kafka_data:

networks:
  nest-network:
