services:
  mysql:
    image: mysql:8.0
    container_name: nest_mysql_auth
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: auth_pass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - nest-network

  mysql_messenger:
    image: mysql:8.0
    container_name: nest_mysql_messenger
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: messenger_db
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: auth_pass
    volumes:
      - mysql_messenger_data:/var/lib/mysql
    networks:
      - nest-network

  nats:
    image: nats:2.10-alpine
    container_name: nest_nats
    ports:
      - "4222:4222"
      - "8222:8222" # HTTP monitoring port
    command: ["-js", "-m", "8222"] # Enable JetStream and monitoring
    networks:
      - nest-network

volumes:
  mysql_data:
  mysql_messenger_data:

networks:
  nest-network:
