// ===== Kafka module =====
export const KAFKA_ADMIN_CLIENT_TOKEN = 'KAFKA_ADMIN_CLIENT';
export const KAFKA_PRODUCER_TOKEN = 'KAFKA_PRODUCER';
export const KAFKA_CONSUMER_TOKEN = 'KAFKA_CONSUMER';
// export const KAFKA_SCHEMA_REGISTRY_TOKEN = 'KAFKA_SCHEMA_REGISTRY';
export const KAFKA_CONFIGURATION_TOKEN = 'KAFKA_CONFIGURATION';
export const KAFKA_HEALTH_INDICATOR_TOKEN = 'KAFKA_HEALTH_INDICATOR';
export const KAFKA_METRICS_TOKEN = 'KAFKA_METRICS';
